### ISSUE TITLE
Dockerhub images: missing Hex and Rebar

### ISSUE THREAD

**Issue by Alainy** [omisego/ewallet#176]
# Dockerhub 

There seems to be a typo on Dockerhub which causes a syntax error.
`docker exec <container-id> mix ecto.create, ecto.migrate` should be `docker exec <container-id> mix do ecto.create, ecto.migrate`.

Also the current latest image doesn't seem to properly install `mix local.hex` and `mix local.rebar`. Since I get the following error:
```
docker exec d5967cfb5a10 mix do ecto.create, ecto.migrate
Could not find Hex, which is needed to build dependency :credo
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :credo from EWallet.Umbrella.Mixfile
```

# Environment

* OS: mac osx 10.12
* Docker: 18.03
* Docker-compose: 1.20

# Steps to reproduce
I used the following docker-compose.yml with `docker-compose up` and after that ran `docker exec <container-id> mix do ecto.create, ecto.migrate` in a seperate window.
```
version: '3.1'
services:
  db:
    image: postgres
  omisego:
    image: omisego/ewallet:latest
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: "postgresql://postgres@db:5432/ewallet"
      LOCAL_LEDGER_DATABASE_URL: "postgresql://postgres@db:5432/local_ledger"
    links:
      - db
```

# Expected behavior
I expected the Dockerfile in omisego/ewallet:latest to properly install local.hex and local.rebar.

# Actual behavior
`$ docker exec d5967cfb5a10 mix do ecto.create, ecto.migrate`
```
Could not find Hex, which is needed to build dependency :credo
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :credo from EWallet.Umbrella.Mixfile
```
