### ISSUE TITLE
Admin Login throws "no function clause matching in Base.url_decode64/2"

### ISSUE THREAD

**Issue by suprtux1** [omisego/ewallet#188]
Issue:

After running mix seed --sample in the ewallet Docker container (docker exec -it omisego_ewallet_1 mix seed --sample) and trying to follow the instructions to login as admin@example.com, the login is denied and the following text is output by the ewallet Docker container:

```
ewallet_1  | 17:38:27.435 request_id=2kmqfgt2as9jim219g0002n1 [info] GET /admin
ewallet_1  | 17:38:27.514 request_id=2kmqfgt2as9jim219g0002n1 [info] Sent 200 in 78ms
ewallet_1  | 17:38:40.124 request_id=2kmqfhkmpvce4nsp2o0002q1 [info] POST /admin/api/login
ewallet_1  | 17:38:40.237 request_id=2kmqfhkmpvce4nsp2o0002q1 [info] Sent 500 in 113ms
ewallet_1  | 17:38:40.239 [error] #PID<0.1125.0> running UrlDispatcher.Plug terminated
ewallet_1  | Server: localhost:4000 (http)
ewallet_1  | Request: POST /admin/api/login
ewallet_1  | ** (exit) an exception was raised:
ewallet_1  |     ** (FunctionClauseError) no function clause matching in Base.url_decode64/2
ewallet_1  |         (elixir) lib/base.ex:482: Base.url_decode64(nil, [padding: false])
ewallet_1  |         (salty) lib/salty/utils.ex:18: Salty.Utils.decode_key/2
ewallet_1  |         (salty) lib/salty/secret_box.ex:53: Salty.SecretBox.decrypt/1
ewallet_1  |         (cloak) lib/cloak.ex:170: anonymous fn/3 in Cloak.decrypt/1
ewallet_1  |         (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
ewallet_1  |         (cloak) lib/cloak.ex:164: Cloak.decrypt/1
ewallet_1  |         (cloak) lib/cloak/types/encrypted_map_field.ex:26: Cloak.EncryptedMapField.load/1
ewallet_1  |         (ecto) lib/ecto/type.ex:647: Ecto.Type.process_loaders/3
```

Compose File: 

```yaml
version: '2.1'
services:
  ewallet:
    image: omisego/ewallet:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
    - DATABASE_URL=postgresql://postgres:password@db:5432/ewallet
    - LOCAL_LEDGER_DATABASE_URL=postgresql://postgres:password@db:5432/local_ledger
    ports:    
    - 4000:4000
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
```

Commands:

```
$ docker-compose up
$ docker exec omisego_ewallet_1 mix do local.rebar --force, local.hex --force, ecto.create, ecto.migrate
$ docker exec -it omisego_ewallet_1 mix seed --sample
```
